### ISSUE TITLE
Tagged releases?

### ISSUE THREAD

**Issue by mjb-yesware** [RobertFischer/JQuery-PeriodicalUpdater#27]
Could you please create tagged releases following the Semantic Versioning scheme (http://semver.org/).

**Comment by RobertFischer** [comment]
No.

There's not really a concept of "releases" for jQuery PeriodicalUpdater. I
always assumed that if you wanted a fixed version, you'd fork it/download
it and manage the concept of "release" yourself. Otherwise, there's just
HEAD that is available, in the belief that HEAD is always better than
not-HEAD.
